//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTin.Core.Models {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iTin.Core.Models.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string CacheWriterNotFound {
            get {
                return ResourceManager.GetString("CacheWriterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ConfigurationFileNotFound {
            get {
                return ResourceManager.GetString("ConfigurationFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string DataSourceNotNull {
            get {
                return ResourceManager.GetString("DataSourceNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string EnumArgumentException {
            get {
                return ResourceManager.GetString("EnumArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ErrorValidatingConfigurationFile {
            get {
                return ResourceManager.GetString("ErrorValidatingConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string FieldText {
            get {
                return ResourceManager.GetString("FieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string FilenameText {
            get {
                return ResourceManager.GetString("FilenameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string IdentifierText {
            get {
                return ResourceManager.GetString("IdentifierText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string InputFileNotFound {
            get {
                return ResourceManager.GetString("InputFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string InvalidColor {
            get {
                return ResourceManager.GetString("InvalidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string InvalidEnumArgumentException {
            get {
                return ResourceManager.GetString("InvalidEnumArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string InvalidFieldDefinitionListText {
            get {
                return ResourceManager.GetString("InvalidFieldDefinitionListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string InvalidFieldNameText {
            get {
                return ResourceManager.GetString("InvalidFieldNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string InvalidFileNameText {
            get {
                return ResourceManager.GetString("InvalidFileNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string InvalidIdentifierName {
            get {
                return ResourceManager.GetString("InvalidIdentifierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string InvalidIdentifierText {
            get {
                return ResourceManager.GetString("InvalidIdentifierText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string InvalidPathText {
            get {
                return ResourceManager.GetString("InvalidPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string InvalidSerieDefinitionListText {
            get {
                return ResourceManager.GetString("InvalidSerieDefinitionListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string InvalidStyleDefinitionListText {
            get {
                return ResourceManager.GetString("InvalidStyleDefinitionListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string InvalidStyleName {
            get {
                return ResourceManager.GetString("InvalidStyleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string MarkPageAsSync {
            get {
                return ResourceManager.GetString("MarkPageAsSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string MissingRootNode {
            get {
                return ResourceManager.GetString("MissingRootNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ModelChartSerieDefinitionErrorText {
            get {
                return ResourceManager.GetString("ModelChartSerieDefinitionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ModelChartSerieFieldDefinitionErrorText {
            get {
                return ResourceManager.GetString("ModelChartSerieFieldDefinitionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ModelChartSeriesErrorCommentLine {
            get {
                return ResourceManager.GetString("ModelChartSeriesErrorCommentLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ModelErrorAttributeLine {
            get {
                return ResourceManager.GetString("ModelErrorAttributeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ModelErrorCommentLine {
            get {
                return ResourceManager.GetString("ModelErrorCommentLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ModelErrorComplexElementLine {
            get {
                return ResourceManager.GetString("ModelErrorComplexElementLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ModelErrorHeaderText {
            get {
                return ResourceManager.GetString("ModelErrorHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ModelErrorSimpleElementLine {
            get {
                return ResourceManager.GetString("ModelErrorSimpleElementLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ModelFieldNameValidSpecialChars {
            get {
                return ResourceManager.GetString("ModelFieldNameValidSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ModelFileNameError {
            get {
                return ResourceManager.GetString("ModelFileNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ModelFileNameInvalidSpecialChars {
            get {
                return ResourceManager.GetString("ModelFileNameInvalidSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ModelFixedFieldDefinitionErrorText {
            get {
                return ResourceManager.GetString("ModelFixedFieldDefinitionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ModelGroupFieldDefinitionErrorText {
            get {
                return ResourceManager.GetString("ModelGroupFieldDefinitionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ModelIdentifierValidSpecialChars {
            get {
                return ResourceManager.GetString("ModelIdentifierValidSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ModelPathNameValidSpecialChars {
            get {
                return ResourceManager.GetString("ModelPathNameValidSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ModelPieceDefinitionErrorText {
            get {
                return ResourceManager.GetString("ModelPieceDefinitionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ModelStyleErrorCommentLine {
            get {
                return ResourceManager.GetString("ModelStyleErrorCommentLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string OutputFileNotFound {
            get {
                return ResourceManager.GetString("OutputFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string PathNotNull {
            get {
                return ResourceManager.GetString("PathNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string PathText {
            get {
                return ResourceManager.GetString("PathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string PieceArgumentOutOfRange {
            get {
                return ResourceManager.GetString("PieceArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string PiecesReferenceNull {
            get {
                return ResourceManager.GetString("PiecesReferenceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ShadowTransparencyPropertyValueOutOfRange {
            get {
                return ResourceManager.GetString("ShadowTransparencyPropertyValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string StyleErrorFormatMessageFieldLine {
            get {
                return ResourceManager.GetString("StyleErrorFormatMessageFieldLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string StyleErrorFormatMessageHeader {
            get {
                return ResourceManager.GetString("StyleErrorFormatMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string StyleErrorFormatMessageNotFound {
            get {
                return ResourceManager.GetString("StyleErrorFormatMessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string TransformFileNotFound {
            get {
                return ResourceManager.GetString("TransformFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string TransformOperationError {
            get {
                return ResourceManager.GetString("TransformOperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string XsdSchemaNotFound {
            get {
                return ResourceManager.GetString("XsdSchemaNotFound", resourceCulture);
            }
        }
    }
}
